_data/members.yml, _data/projects.yml
This pull request adds PlasmaPy to the list of projects and myself as one of the members.
Thanks!
-Nick
=> Add PlasmaPy project and member

_data/members.yml, _data/projects.yml
Updated SpacePy project info, including github URL, location of docs,
and corrected logo. Added Steve Morley to members including github
handle.
=> Updating SpacePy data and adding SpacePy contact to members.

_pages/meetings.html
Added a section for telecons and linked to slides on google drive
=> Updating meetings.html

_pages/meetings.md
Added AGU session and google cal link; added links to content from meeting.
=> Updated meetings page

index.html
=> Updating the About Section

_config.yml
Removed the verbiage use "A website to...", which doesn't make sense when read... on a website.
=> Updating tagline

_data/taxonomy.yml
Adding a yaml file with include the categories of keywords and their associated keywords from hackathon session at PyHC 2019
=> keywords for taxonomy

_data/projects.yml
Now without duplicates (as far as I can tell)
=> Added keywords to _data/projects.yml

_data/projects.yml
Add sami2py to list of projects
=> add sami2py

_pages/contact.md, _pages/meetings.md
Added new meeting dates in meetings page, also adding more info about joining the Google Group after running into some confusion/snags with people trying to join the group.
=> Updating meeting page, plus clarifications for google group

_data/projects.yml, _data/projects_core.yml, _includes/project_cards.html, _pages/projects.html
This is an attempt to separate out some 'core' projects and put them at the top of the project page. I appreciate this is a bit subjective, so am open to other suggestions for projects to add/remove, but I think as a minimum the 'core' projects should conform to our standards (https://github.com/heliophysicsPy/standards/blob/master/standards.md)
=> Separate out core projects

_pages/meetings.md
Includes new telecon time info and the 2019 Fall Meeting Notes link.
=> Updated Meeting Page

_pages/meetings.md
Specifically, updating the AGU poster session link at the bottom of the Meetings page.
=> Updating Meeting Page

_pages/meetings.md
Short-ish write up of Fall 2019 meeting for documentation purposes.
=> Adding in meeting report for Fall 2019 meeting

_pyhc_projects/README.md, _pyhc_projects/adding_to_pyhc_project_list.md
Some minor wording changes to make things sound better.
=> Quick wording changes

_data/projects.yml
I added AFINO to the list of projects on the PyHC site. AFINO is a time series analysis tool and is one of the projects currently funded for development by the HDEE solicitation.
I have not yet completed the self evaluation. I'll create a follow-up PR once that is done.
=> Added AFINO to projects.yml

_pages/meetings/april2020.md, _posts/2020-02-27-spring-2020-meeting-announced.markdown
This states that we'll hold the meeting remotely if we need to cancel in-person attendance.
=> Add contingency plan to the website

_pages/meetings/april2020.md
=> Near-final updates to spring meeting page

_data/projects.yml
I'm adding in the enlilviz package to the projects list. I went through and added a quick self-evaluation as well.
**Community Standard**
I am currently the only contributor, so I'm calling this partially met because of that. It is fully open source under an MIT license so anyone can contribute.
**Testing Standard**
I have automated tests, but have not been rigorous on testing every individual unit of the code. It could be improved, so I'm calling this partially met.
=> Adding the enlilviz package.

_data/projects.yml, _data/projects_core.yml
Self-review for the fiasco and sunpy packages according to the PyHC standards and project review guidelines
=> Self-reviews for fiasco and sunpy

_data/projects.yml
Going to test out the suggested template in #95.
1. Community
2. Documentation
3. Testing
4. Software Maturity
5. Python 3
6. License
=> update and self-review sami2py

_data/projects_core.yml
I originally rated community as "Partially met", as I didn't think there were any contribution guidelines. I was wrong though and there are (https://docs.heliopy.org/en/stable/development/contributing.html), so I've updated this to "Good".
=> Update heliopy ratings

_data/projects.yml
All green except testing; coverage of some modules is limited.
=> Add standards badges for SpacePy.

_data/projects_core.yml
Using template from #95.
This is based on the [PyHC Project Review Guidelines](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/_pyhc_projects/pyhc_project_grading_guidelines.md). Numbers in square brackets refer to the item in the [PyHC Standards](https://github.com/heliophysicsPy/standards/blob/master/standards.md).
1. Community
2. Documentation
3. Testing
4. Software Maturity
5. Python 3
6. License
=> Add self-review and updates to pysat

_data/projects.yml
This PR adds the ndcube package review.
=> ndcube 2020 review

_data/projects.yml
* Project name: aidapy
* Python package developed within the H2020 European project AIDA. The main goal is to provide machine learning and statistical methods to the heliophysics community.
* The grade for the community standard: Partially met. We still need a code of conduct.
* The grade for the documentation standard: Partially met. We have documentation but some parts are missing.
* The grade for the testing standard; Partially met. We have unit testing and automatic CI but the coverage is still low (about 65%)
* The grade for the software maturity standard: Partially met. We plan to work on an official release and proper packaging.
* The grade for the Python 3 standard: Good.
* The grade for the license standard: Good.
=> Add aidapy project ans self-review

_data/members.yml, _data/projects.yml
This PR is using the draft from #95 
This is based on the [PyHC Project Review Guidelines](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/_pyhc_projects/pyhc_project_grading_guidelines.md). Numbers in square brackets refer to the item in the [PyHC Standards](https://github.com/heliophysicsPy/standards/blob/master/standards.md).
1. Community
2. Documentation 
3. Testing
4. Software Maturity
5. Python 3
6. License
Note: Also updated by affiliation in the member list.
=> Aburrell community

_data/projects.yml
We've been using the READMEs for documentation, so I'm pointing to our GitHub page for docs; we'll update this to readthedocs once we have that set up.
=> Adding pySPEDAS

_data/projects.yml
Summary of missing points needed to make all green:
1. Community (Partially met)
- Lacking code of conduct
- Lacking contributing guide
2. Documentation (Good)
3. Testing (Partially met)
- Incomplete automated test coverage (coveralls reports 40%), though there are procedures in place for integration and acceptance testing
4. Software maturity (Good)
- available through PyPI but not conda - as far as I could tell conda is not a hard requirement(?), though I anyway plan to add it
5. Python3 (Good)
6. License (Good) (MIT style)
I plan to address the gaps within the next month.
=> Add viresclient self-review

_data/projects_core.yml
Here's the self-evaluation for PlasmaPy, which is a core Python package for plasma science.  We're still early in our development compared to (for example) SunPy, so I put software maturity as "partially met", but otherwise all of the standards are met.
=> Add PlasmaPy self-evaluation

_data/projects.yml
Added the self-evaluation metrics for the AFINO package.
=> AFINO self-evaluation

_data/projects.yml
1. Community
1. Documentation
1. Testing
1. Software Maturity
1. Python 3
1. License
=> Added OMMBV

_pages/meetings.md
AGU 2020 abstract submissions are live! adding information for where to submit an abstract to the PyHC session.
=> Adding information for AGU 2020 abstract submissions

_data/projects.yml
Added a link to the OCBpy logo in the OCBpy project card.
=> DOC: added ocbpy logo

_data/members.yml
If I did this right, this PR should add my profile to the people page....
=> Add Jon Niehof to people page

_data/members.yml
People sent me their names and GitHub handles, and I added them here. 
I also removed one person whose GitHub account does not exist anymore.
=> Add members

_posts/2021-03-02-spring-2021-meeting-announced.markdown
Created blog post to announce the PyHC spring 2021 meeting dates. This will be updated later on to include the meeting web page when it's live. Looking for grammar/spelling checks here. :)
=> Adding blog post announcement for spring 2021 meeting

_pages/docs/reports.md, _pages/docs/reports/february2021.md
Wrote up a quarterly report for Feb 2021. Added it to the Reports web page here.
=> Adding in the feb 2021 quarterly report to the website

_data/projects_core.yml
This PR adds keywords from the taxonomy for SpacePy.
=> Add keywords for SpacePy

_data/members.yml, _data/projects.yml
Closes #159.
Adds geopack to our projects. I haven't given it any keywords or grading badges. But we also haven't decided if we even want to merge this, so those can wait until the decision is made.
=> Add geopack to projects

_data/projects.yml, _data/projects_core.yml, _data/taxonomy.yml
=> Update taxonomy and viresclient

_pages/docs/meeting_reports.md
Just a check to make sure I didn't do anything wild. :)
=> Adding spring 2021 meeting doi to biannual meetings page

_pages/docs/suggested_tools.md
Self-explanatory. I've been so impressed using Deepnote for our paper project that I decided it belongs here.
=> Add Deepnote to suggested tools

_pages/meetings/fall2021.md
Title is pretty self explanatory. :)
=> Adding fall 2021 meeting zoom recordings to meeting web page

_data/projects.yml
`hissw` is a very lightweight (~1 file) package for easily incorporating IDL (and specifically SolarSoft) scripts into your Python workflows. Nothing about this code is necessarily specific to solar or heliophysics as well, but it does target technologies (i.e. IDL) that are often-used in this community and it also enables systematic comparison between IDL and Python implementations, something that may be very useful to those in the PyHC community.
* [Docs](https://wtbarnes.github.io/hissw/)
* [GitHub](https://github.com/wtbarnes/hissw)
=> Add `hissw` package to the  project page

_pages/meetings.md
Updated info about our PyHC AGU session, now that it's been assigned a date and time. Quick check to make sure I didn't make any silly typos, etc. :)
=> modifying 2021 AGU info on Meetings page

_data/projects.yml, _data/projects_core.yml
As mentioned at the PyHC Fall 2021 Meeting, there's interest in having pySPEDAS be included as part of the PyHC Core Packages. Officially putting this idea forward here.
=> Requesting addition of pySPEDAS to the PyHC Core Packages

_data/members.yml
Just tagging you @sapols to let you know that I finally got to this. :)
=> Adding Eric Grimes to Peoples page

_data/projects.yml
OMMBV provides unit vectors and scalars for mapping electric fields and ion drifts along multipole magnetic fields. I assigned the project "Good" in all categories. OMMBV reports 100% testing code coverage (via coveralls) via unit testing using GitHub workflows. OMMBV has documentation, code of conduct, a developed readme, and a logo. OMMBV is generally considered 'complete' at the moment pending additional funding to optimize and/or reduce performance. An update may be released to support field line tracing starting at altitudes below the target altitude to support ground based users. 
I removed pysatMagVect as that is the old name for OMMBV. If it needs to stay for documentation reasons then that is ok with me.
=> Update OMMBV in projects.yml

_pages/meetings.md
I guess it doesn't like trailing slashes.
=> Fix broken summer school link

_posts/2022-02-10-pyhc-summer-school-2022-announced.markdown
Now that the web page is live, created a blog post announcement for our 2022 Summer School! Grammar, content, etc. check appreciated.
=> Adding a blog post announcement for the PyHC 2022 summer school

_pages/meetings/summer_school.md
Closes #201 
Just FYI, I added it to the page. I'm gonna merge this immediately.
=> Clarify official summer school language

_data/projects.yml
Adds [dbprocessing](https://spacepy.github.io/dbprocessing/) as a new PyHC package. This work was funded via the 2020 HDEE call.
=> Add dbprocessing as new project

_config.yml, _includes/head.html, _pages/meetings/summer_school.md
Trying out changes I found in [this post](https://brianbunke.com/blog/2017/09/06/twitter-cards-on-jekyll/#tldr-too-long-didnt-read) to fix Russell's request in #204
=> Making changes so that twitter renders links to PyHC site with images

_pages/contact.md
Hard for people to know these resources exist if they aren't advertised. :D Adding that info here.
=> Adding PyHC twitter and PyHC Helionaut info to our contact page

_pages/docs/reports.md, _pages/docs/reports/february2022.md, _pages/docs/reports/november2021.md
Added the Feb '22 report I just made today. Realized I'd forgotten to add the Nov '21 report, so added that one too.
=> Added Nov 2021 and Feb 2022 Quarterly Progress Reports

_pages/contact.md, index.html
Just an FYI: I added telecon info to our contact page, and made the telecon/meeting info on the home page more explicit. 
I'm merging this right away.
=> Shawn update contact

_pages/meetings/summer_school.md
Closes #218.
@jibarnum, if you think the text is fine I will merge this.
=> Add recommended hotel

_pages/meetings/summer_school.md
Closes #222.
This PR adds:
- Mention that presentations will be recorded and streamed to YouTube
- ESAC room numbers
- Bus details
- Updated agenda details
- In-person vs virtual presenter info
Suggested in the issue but intentionally left out:
- Whether most attendees will be using the same hotel (impossible to say)
- Where's a good place to get food near the hotel (people can Google restaurants)
=> Update summer school details

_pages/meetings/summer_school.md
Self-explanatory.
I'm going to merge immediately in the interest of getting this information out ASAP. @jibarnum if you have any suggestions, feel free to make them here and I'll update accordingly.
=> Add a COVID-19 Rules section

_pages/meetings/summer_school.md
=> adding VirES to summer school schedule

_pages/meetings/summer_school.md
This PR updates the agenda to reflect the current spreadsheet, and it adds more to the COVID-19 Rules section.
@jibarnum I tried to make this as succinct as possible to guard against people seeing a large covid paragraph and glossing over it. I'm open to suggestions, otherwise, I'll merge.
=> Summer School page updates

_pages/docs/reports.md, _pages/docs/reports/may2022.md
See title. Copy+paste from email I sent a little bit ago today.
=> Added May 2022 quarterly report to the website

_pages/meetings/summer_school.md
Just a section with a short couple sentences pointing people to the summer school github repo.
=> Add link to summer school github repo

_data/projects.yml, _data/projects_core.yml
Hi Shawn,
I finally got around to updating the Kamodo info and adding the badges. Please add Kamodo to the core package list as we discussed a while back. Thanks!
Rebecca
=> Adding Kamodo information

_pages/docs/reports.md, _pages/docs/reports/august2022.md
Already sent this off to Aaron et al. yesterday, this PR is for posterity's sake.
=> Adding in August 2022 quarterly report

_pages/meetings/spring2022.md
Threw the links for days 1, 2, and 4 recordings on the spring 2022 mtg web page.
=> Adding spring 2022 mtg recordings

_data/projects.yml
SkyWinder is an open-source Python package useful for instrument control, telemetry, and image analysis. It is adapted from software that successfully managed flight control, telemetry, preliminary image analysis, and data visualization for a balloon-borne mission and it has broad uses for mid- and upper-atmosphere science instrumentation including aurora, cloud, and airglow imagers.
This software consists of two distinct parts: the flight and analysis modules. The SkyWinder flight package includes modular distributed flight control including telemetry and subsystem coordination for running mobile aeronomy experiments such as balloon-borne payloads, airplanes, sounding rockets, and suborbital reusable launch vehicles (sRLVs), as well as isolated semi-autonomous ground instruments. The …
=> Add SkyWinder to PyHC project list

_pages/meetings.md, _pages/meetings/fall2022.md
- added in recording for Days 1 and 2 of Fall 2022 meeting
- updated info for our 2022 AGU sessions
=> Meeting Page updates

_pages/meetings/fall2022.md
=> Adding Fall 2022 Meeting Recordings

_data/projects.yml
GeospaceLAB provides a standard framework for data access, analysis, and visualization in space physics and space weather. The main functionality includes: 
- Standard data interface to manage various data from observations and simulations.
- Standard visualization dashboard to plot time-series data and geospatial data.
- Unified interface for coordinate transformation.
The main functionality has been tested well. The documentation of the core classes and modules is ready, however, detailed descriptions and extensions should be added in the coming month.
=> Add GeospaceLAB to the PyHC Project list

_posts/2022-02-25-spring-2022-meeting-announced.markdown, _posts/2023-01-05-ror-id.markdown
Adding a blog post about our ROR ID.
=> Write blog post about new ROR ID

_data/projects_core.yml
new documentation website, new contact info, and updated badge statuses.
=> Updating Kamodo info

_data/projects.yml, _data/taxonomy.yml
This PR is to add [XRTpy](https://xrtpy.readthedocs.io/en/latest/) ([repo](https://github.com/HinodeXRT/xrtpy)) as a PyHC project.  It also adds `"hinode"` to the taxonomy.
This PR is of interest to @joyvelasquez & @jslavin.
=> Add XRTpy as a PyHC project

_pages/meetings/spring2023.md
Simply appending _"Parking passes will be provided and there is free wifi."_ to the "Meeting Location" section.
=> Add parking and wifi info

_posts/2023-04-27-spring-2023-meeting-announced.markdown
=> Make Spring 2023 Meeting blog post

_data/projects.yml
Sorry, i accidentally created a branch for this which I did not mean to do! Should have done it from my fork.
=> Added CCSDSPy to package index

_data/projects.yml
THIS IS A TEST, THE PR WILL BE REVERTED.
=> Add my-pyhc-package to projects

_data/projects.yml
=> Add my-pyhc-package

_data/projects.yml
Name: pyDARN
Description:  pyDARN is an open source python library for data visualization of SuperDARN data.
Standards:
- community:  Good
- documentation: Good
- testing: Partially met (no automated testing - can be implemented in near future)
- software maturity: Partially met (no conda installation)
- python3: Good
- license: Good
=> Requesting Update for pyDARN Package Information

_data/projects.yml, _data/projects_unevaluated.yml, _includes/project_cards_unevaluated.html, js/projects.js
This PR fixed some bugs that lingered after we merged [the PR to separate unevaluated projects into their own table](https://github.com/heliophysicsPy/heliophysicsPy.github.io/pull/260), namely:
- Remove empty badge columns from rows of the unevaluated table
- Implement the search/filter functionality for the unevaluated table
I also added a few new project evaluations that I'd done myself a while ago but never made public until now.
=> Clean up unevaluated projects table

_pages/docs/reports.md, _pages/docs/reports/february2023.md, _pages/docs/reports/may2023.md
Closes #283. Converted the two reports into markdown and added them to our site.
=> Add two quarterly reports

_pages/meetings.md
Closes #288. Just updating the AGU text per the issue.
=> Update AGU info

_data/projects.yml
Hi there, 
This is Yu Chen, and I can be reached at yc0020@uah.edu. I just added PyGS package to this projects.yml and would like to publish our package to PyHC. Please let me know if there is anything I need to add.
=> Add PyGS package

_data/projects.yml
Hi there,
We have added the code of conduct and contributing files. We've also fixed the address of PyGS code.
=> PyGS: Change community to "Good"

_pages/docs/reports.md, _pages/docs/reports/august2023.md
ignore the name of the branch, it's 8 PM and I'm still working... this is actually the august 2023 report. Only requesting review to tag you @sapols that this is going through.
=> adding in aug 2023 quarterly report to website

_pages/meetings.md, _pages/meetings/fall2022.md
Self explanatory title. Posting PR here for posterity's sake.
=> adding fall 2022 meeting report, and changing links to point to PyHC YT channel

_data/members.yml
I added myself as discussed in #299 . Thanks!
=> Add Marcus Hughes as a member

_data/projects.yml
SciQLop has quite some red badges but that would be nice if we can advertise it a bit.
=> Adds SciQLop and PyCDFpp projects and update a bit Speasy entry

_data/projects.yml
Updated links to new repository location under Cosmic Studio brand
=> Update projects.yml for OMMBV

_data/projects.yml
PyRFU is a free and open-source data analysis package based on the well-known irfu-matlab library. 
Community: Partially met. The PyRFU is still small, with Louis Richard being responsible for all the code development. Contributions are expected in the upcoming months. 
Documentation: Good. 
Testing: Partially met. The PyRFU package is partially tested (73%). Improvements are planned for the upcoming months.
Software Maturity: Good.
Python 3: Good.
License: Good.
=> Update projects.yml with PyRFU

_pages/meetings/community_meetings/spring2024.md
Self explanatory. PR for posterity purposes.
=> Added links to spring 2024 recordings

_pages/meetings/conference_sessions/conference_sessions.md
=> Adding info for AGU and DASH/IHDEA sessions

_data/projects.yml
The amisrsynthdata package is designed to generate synthetic data for the Advanced Modular Incoherent Scatter Radars (AMISR).  [AMISR](https://amisr.com/amisr/) is used for a wide variety of research in ionospheric dynamic and is a highly flexible and adaptable system.  This package is intended to help plan new observational modes and validate high-level data products.
**Community:** Good
**Documentation:** Good
**Testing:** Partially met
**Software Maturity:** Partially met
**Python3:** Good
**License:** Good
The Testing and Software Maturity standards are both marked as "Partially Met" due to some incomplete testing (88% coverage) and the fact that many of the tests currently fail due to floating point errors and need to be revised.  We intend to research how to better conduct these …
=> Add amisrsynthdata to PyHC List

_data/projects.yml
- Update docs link for solarmach
- Update status of community and testing for solarmach & solo-epd-loader
=> Update solarmach & solo-epd-loader in projects.yml

_data/projects.yml
Hi there!
This PR is to add our PyAuroraX project to the PyHC list.
PyAuroraX is one of the client libraries that the AuroraX project has developed to support data access and analysis support tools for working with auroral ground-based data and models (all-sky imagers, spectrographs, TREx Auroral Transport Model, etc.). You may remember about it from my last few years of AGU talks/posters...sorry, we've been a bit side-tracked with things and meant to add this a bit earlier!
Here's a breakdown of the grades I figured based on the self-assessment:
- Community - good
- Documentation - good
- Testing - good
- Software Maturity - good
- Python 3 - good
- License - good
Some notes:
- PyHC guidelines point 3: Conda package is in the works, along with prebuilt wheels for as many platforms and OS …
=> Add PyAuroraX project

_pages/meetings/community_meetings/community_meetings.md, _pages/meetings/community_meetings/fall2024.md
Adding a meeting page to point people to for the Fall 2024 meeting
=> Fall 2024 Meeting

_pages/docs/reports.md, _pages/docs/reports/august2024.md, _pages/docs/reports/february2024.md, _pages/docs/reports/may2024.md, _pages/docs/reports/november2023.md
Not looking for grammar/spelling this time (they're already submitted to NASA), just a code check for sanity.
=> Adding in backlog of quarterly reports

_pages/meetings/community_meetings/community_meetings.md
Wooooooo she exists! https://zenodo.org/doi/10.5281/zenodo.13687776
=> Adding in spring 2024 meeting report

_pages/meetings/community_meetings/community_meetings.md
She is done. She is robust. She is long overdue.
=> Added link for spring 2023 meeting report

_pages/docs/suggested_tools.md
=> Adding in link for Software Heritage on Suggested Tools page

_data/projects.yml
We moved the docs, so I updated it in the table.
=> update regularizepsf docs link

_pages/meetings/community_meetings/fall2024.md
Updates agenda outline and meeting location (in SPSC now instead of LSTB)
=> couple quick updates to fall 24 page

_pages/meetings/conference_sessions/conference_sessions.md
- Updated AGU to have info specific to the PyHC session and other relevant sessions, posters, and talks and removed information on abstract submission
- Removed DASH/IHDEA meeting info
=> Updates to Conference Sessions page

_pages/meetings/community_meetings/fall2024.md
Self explanatory. Already checked links are correct. Making a PR for posterity's sake, but going to go ahead and merge right away. @sapols
=> Adding recordings to fall 2024 meetings page

_data/members.yml
=> Add a new member

_pages/docs/meeting_reports.md, _pages/meetings/community_meetings/community_meetings.md
Closes #362 
Simply adding links to the 2024 Fall Meeting report.
=> Add links to 2024 Fall Meeting report

_pages/meetings/community_meetings/spring2025.md
Pretty self explanatory. Tagging you here @sapols to let you know I put the links up and immediately merged the PR.
=> Adding YouTube recording links for spr 25 meeting
