heliophysicsPy/heliophysicsPy.github.io

- _data/members.yml
- _data/projects.yml
Existing spice wrapper referenced is not developed actively, spiceypy is newer/ more complete.
So I think it is fair to list both ;)
> Adding SpiceyPy to projects and myself (Andrew Annex) to members files.

- README.md
Issued a connection not private warning on my browser. If this is the case, we might want to indicate as such in the url.
> Removed secure from https

- _pages/contact.md
Updated the page to now show instructions for how to join our Google Group mailing list, instead of the LASP-managed Sympa mailing list.
> Updating the contact page

- _posts/2019-09-05-fall-2019-meeting-announced.markdown
It will now include a link to the meeting's main website so people can register and get other important information.
> Updating the Fall 2019 Meeting Announcement

- _includes/project_cards.html
- _pages/projects.html
Fixes #64.
The issue was that the ids for the "Core" and "Other" project tabs were conflicting. This injects an additional variable to make the ids unique. If someone has a more elegant fix for this, please chime in! This feels a bit hacky.
> Fix project cards

- _pages/meetings.md
Says Fall 2020, but should say Spring 2020.
> fixing typo in spring meeting info

- _pages/meetings.md
We should merge this one soon to make sure the information is accurate on the meeting webpage.
> Fix typo in meeting dates & add link to SHINE tutorial description

- _data/projects.yml
The pythonhosted.org SpacePy docs haven't been definitive for some time now (and I was finally able to get those deleted.) This PR updates the links to the correct site on github.
> Update SpacePy docs site to github.io

- _data/projects.yml
This package provides access to the ESA Swarm mission data and models. It's part of a larger server/client architecture "VirES" supported by ESA, principally for Swarm, though could evolve to other datasets in the future (VirES for Aeolus is in development). GUI access is at https://vires.services and there is also now a free "Virtual Research Environment" at https://vre.vires.services (a JupyterHub deployment) where we plan to provide ready-to-run notebooks soon.
The server can provide flexible access to time series of most of the Swarm products, together with on-demand evaluation of geomagnetic field models. viresclient accesses this server and returns requested data as pandas or xarray objects.
> Add viresclient to Projects

- _pages/meetings.md
Adding link to Google Drive folder that houses all Spring 2020 meeting notes, documents, agenda, etc.
> Adding in link to Spring 2020 meeting Google Drive folder

- _posts/2020-02-27-spring-2020-meeting-announced.markdown
Adding a blog post for the Spring 2020 Meeting. This can be distributed to whomever seems relevant.
> Adding blog post about Spring 2020 Meeting

- _pyhc_projects/adding_to_pyhc_project_list.md
The instructions for adding a new project to the pyhc list have a typo in the example for partially-met; it's "paritally-met". This PR just swaps the letters....
> Fix typo in partially-met example (adding project instructions)

- README.md
This addresses issue #93.
The URL text had HTTP in the URL but the link embedded behind the text used HTTPS. I assume that was a typo.
> Correct link in README by changing HTTPS to HTTP

- _data/projects.yml
- _data/projects_core.yml
This PR moves SpacePy from "projects" to "core projects". The question came up on the call today why SpacePy wasn't listed as core; it's designed as a broadly useful (rather than task-specific package) and in particular the CDF support was cited as a general capability.
I'm submitting this PR since the SpacePy team supports moving SpacePy to the core section, but further discussion can certainly happen here.
> Move SpacePy to core packages

- _data/projects.yml
- _includes/project_cards.html
This PR adds a conditional that alters the FontAwesome icon for the code repo if the repo is on GitLab. This is a bit hacky and doesn't generalize well to other kinds of repos (e.g. Bitbucket). If there is a better option for doing this, I'm very open to it.
> GitLab icons for GitLab repos

- _data/projects.yml
I noticed that every PR in this project fails the automated checks because of mixed HTTP/HTTPS content. This has apparently been an issue for a while. Upon closer inspection, the offending content is two logos: the logo for DASCutils and the logo for THEMISasi.
I decided to take executive action on this and host these two logos securely. This PR swaps the old HTTP URLs for new HTTPS ones, which will fix the automated checks for all our PRs. 👍
> Replace two HTTP logo URLs with HTTPS URLs

- _data/projects.yml
- _data/projects_core.yml
Closes #122.
Some [project cards](http://heliopython.org/projects/) weren't displaying logos because the URLs to the images were broken. Affected projects were:
- pysat
- GOESutils
- NDCube
- OCBpy
It wasn't hard to see what files the old URLs were pointing to and then track down their new locations.
> Fix broken project logo URLs

- _data/projects.yml
AACGMV2 now meets the pyHC testing standards, updated badge to reflect this.
> DOC: updated aacgmv2 testing standards

- _pages/meetings.md
Adding link to meeting report for fall 2020 meeting (and spring 2020 meeting when I noticed it wasn't there). Also, removed now outdated AGU info from meeting page.
> Adding in meeting report links to meeting page, etc.

- _pyhc_projects/package_review_template.md
This closes #95. We've been using that GitHub issue for a while as a temporary holding place for a draft of this template. I finalized the draft a couple months ago and it's ready to join this repo. I'm putting it in with the other similar markdown files (both of which are referenced in this template).
You can see it rendered here while the feature branch exists: https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/shawn-package-review-template/_pyhc_projects/package_review_template.md
> Commit Package Review Template

- _pages/contact.md
The old method for some reason stopped working as it used to... instead of getting to the request to join page, you ended up at a page that showed all the pyhc list emails, but no option to join anywhere. Found a different way that people can join the list, which is also much simpler than the old method. Silver lining.
> modifying instructions on how to join mailing list

- _data/projects.yml
The latest apexpy release (1.1.0) fixed the existing issues with integration testing.  The coverage is now at a level that may be considered "good".
> Updated apexpy testing badge

- _pages/docs.html
- _pages/docs/meeting_reports.md
Closes #165 .
I created a new sub page that houses biannual meeting reports, and modified the documents page to point to this new sub page. Question to consider - if we have Zenodo links for all meeting reports, do we still want to link to the meeting reports stored in the G-Drive (on our Meetings page)? Or, do we want to point people to our Documents page for all meeting reports?
> Adding past biannual meeting DOIs to the website

- _pages/meetings.md
Now that abstract submissions for AGU 2021 are open, wanted to get the link for that on our website. Also, updated related meetings to remove old meetings and include the 2021 Hack Week by PlasmaPy.
> Update meetings page

- _pages/meetings.md
- index.html
Quick PR to correct the meetings page now that the Spring 2021 Meeting is over. 
I also saw an opportunity to paste the sentence we have about our Google Calendar on the home page. That starts to address Aaron's complaints about that stuff not being easy to find.
> Update meetings page, add calendar link to home page

- _pages/meetings.md
- _pages/meetings/fall2021.md
- _posts/2021-08-09-fall-2021-meeting-announced.markdown
This PR adds a Fall 2021 meeting page and links to it in the blog post. The format was based off the Spring 2021 page. I got the info/links from the Google Drive, but @jibarnum please make sure everything is accurate.
> Create Fall 2021 meeting page

- _pages/docs/meeting_reports.md
- _pages/meetings.md
I created a meeting report for the Fall 2021 meeting on Google Drive and put it on Zenodo. Adding links to all that here.
> Adding fall 2021 meeting report links

- _pages/meetings/summer_school.md
Preregistration is now just "registration".
Direct people to email "pyhc-confidential@lasp.colorado.edu" instead of either Julie or Shawn directly.
> Update summer school email and registration

- _pages/docs.html
- _pages/docs/python_resources.md
- _pages/meetings.md
- _pages/meetings/summer_school.md
Closes #205.
This PR adds a new "Python Resources" page that lives under "Documents". I added a section to the summer school page that links to this new info. The links are those shared in issue #205. I figured they were a good enough starting point, and we can always add to/modify this page later if we find new material to share.
**Let me know if you like the general structure and how I worked it into the flow of the summer school page. Input on wording choices etc. are totally welcome.**
(Note, while I was in there, I also found a way to make the summer school links in the "Meetings" page relative to the site's base URL, which supports local development.)
> Add Python Resources

- _data/projects.yml
Hello,
Here is a PR to add Speasy into PyHC projects list. We will add more packages from SiQLop project soon.
Speasy is the most mature project for the moment and is already in use.
> Adds Speasy to projects list

- _pages/meetings/fall2020.md
- _pages/meetings/fall2021.md
- _pages/meetings/spring2021.md
CU decided that our G-Drive storage limits are shortly to be 5 GB. That obviously won't work. However, our CU OneDrive accts can have up to 5 TB. Moved all Zoom recordings I had for PyHC meetings to my CU OneDrive, and fixed links on our meeting pages. Mainly posting this PR to make sure that those recordings are viewable to others.
> Moving PyHC Meetings' Zoom Links

- _data/projects.yml
**solo-epd-loader** is a small package whose only goal is to provide data of Solar Orbiter's Energetic Particle Detector (EPD). It downloads the data from ESA's [Solar Orbiter Archive (SOAR)](http://soar.esac.esa.int/soar) if needed. The functionality is partly available also in SunPy, but there only in a general way. In addition, here the aim is (in the future) to further process the data because some of the data products are not really final.
PyHC standards that are not _good_:
- **Community** ("Partially met"): Collaboration encouragement/guidelines missing.
- **Testing** ("Requires improvement"): Mostly missing and only done manually so far, but planned for the future. Shouldn't be too bad because the functionality is relatively small.
> Add project solo-epd-loader

- _data/projects.yml
**solarmach** is a small package that provides a multi-spacecraft heliospheric configuration plotter to analyse the location and magnetic connection of the heliospheric spacecraft fleet at a given time. For this, it utilizes SunPy's get_horizons_coord() functionality to obtain spacecraft ephemeris from JPL HORIZONS, calculates the nominal (solar-wind-speed dependent) Parker heliospheric magnetic field lines, and visualize the results.
PyHC standards that are not _good_:
- **Community** ("Partially met"): Collaboration encouragement/guidelines missing.
- **Testing** ("Requires improvement"): Mostly missing and only done manually so far, but planned for the future. Shouldn't be too bad because the functionality is relatively small.
> Add project solarmach

- README.md
I extended the description of the "Add software package" section to include a link to the document [Adding a Project to the PyHC Project List](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/main/_pyhc_projects/adding_to_pyhc_project_list.md) that contains the necessary information on the self evaluation. This file was only linked on https://heliopython.org/projects/
In addition, some small writing adjustments
> Add link to "Add software package" on main  README.md

- _pages/meetings/summer_school.md
The previous link for Solar-MACH was pointing to the initial GitHub repo that is not really maintained any more. Link now points to the current version that provides the pypi/conda packages.
> Changing link to Solar-MACH on summer school page

- _pages/meetings.md
- index.html
This PR excites me. I found a way to display our Google Calendar directly on the website without people having to click any links nor sign into Google! 
I added the calendar to the "Calendar" sections of our homepage and Meetings page.
@jibarnum is your dev environment set up to run this repo locally with `bundle exec jekyll serve`? I've only tested this locally on my machine and it'd be good to make sure it works on others before we merge. But if not, we can always just merge anyway and "do it live."
> Display Google Calendar directly on website

- index.html
Simple, self-explanatory change to show only 3 blog posts on the homepage rather than the current 5. 
This was the last homepage change I'd planned back when we were discussing how to improve the homepage. The two main requests were 1) better display telecon times and 2) remove focus on repetitive blog posts.
1) Was accomplished by displaying our Google Calendar directly on the website.
2) Is accomplished by this change—3 posts personally feels like a lot less to scroll past, and we're less likely to repeat ourselves in just the most recent 3 posts.
> Limit homepage blog posts to 3 instead of 5

- _pages/meetings.md
- _pages/meetings/spring2023.md
Closes #265.
This PR creates the web page and adds it to the Meetings page. No blog post announcement yet.
The page is pretty similar to past pages, but I updated the layout slightly to accommodate in-person info and prioritize registration. Note the use of Google Maps links/embedding to give people directions. 
Also note the "_(work in progress)_" notes under Session Documents and Presentations.
> Make Spring 2023 Meeting page

- _pages/docs.html
- _pages/docs/adding_to_pyhc_project_list.md
- _pyhc_projects/adding_to_pyhc_project_list.md
This PR makes the project addition instructions more discoverable by adding them to the Documents page.
> Add PyHC project addition instructions to docs

- _data/projects.yml
This PR adds [regularizePSF](https://github.com/punch-mission/regularizepsf) as a PyHC project. regularizePSF is a new tool made as part of the PUNCH mission (but applicable generally) to correct variable point-spread functions in images. 
I marked everything as green/good since I feel like we've adhered to the expected standards. Feel free to suggest otherwise if you see something missing. 
Also, I was a bit confused what keywords were acceptable. I did find the taxonomy mentioned in the SkyWinder PR, but it could be helpful to add that bit of instruction to the instructions for adding a project (or maybe it's there and I missed it). 
Finally, PUNCH might be added to the "Mission" taxonomy in the future. We will release more PUNCH specific packages. I didn't tag this one that way since …
> Adds regularizePSF as a PyHC project

- _pages/meetings/spring2023.md
Closes #284. Simply adding the links to the YouTube videos to the meeting page.
> Add links to meeting recordings

- _data/projects_core.yml
@drsteve is still listed as the SpacePy contact on the projects page; I've been doing more PyHC stuff so we agree it makes more sense for me to be the contact.
> Switch SpacePy contact to Jon Niehof

- _pages/contact.md
- _pages/docs/adding_to_pyhc_project_list.md
- _pyhc_projects/adding_to_pyhc_project_list.md
This PR fixes the links to our Matrix chatroom from the old riot.im to the new element.io. I only did this in "normal" pages; I did not change meeting minutes or other records that had the old link.
> Change old Matrix "riot.im" links to "element.io"

- _pages/meetings/summer_school_24.md
Updated the Summer School web page to have the most up-to-date information. Asking for a quick once over to be sure nothing is glaringly wrong. We should push this soon, and get it more publicized on the overall PyHC website as well.
> '24 Summer School Updates

- _includes/header.html
- _pages/meetings.md
- blog/index.html
**This PR does three things:**
1. Adds a new nav item "**Summer School**" to the top site menu
- Temporary: I'll remove it this year after the summer school
- Bolded to draw attention
2. Adds an entry for this year's summer school to the Meetings page
3. Fixes a bug where "Blog" in the nav menu wasn't switching to black font when you're on the page
**Questions for Julie:**
1. We should make a blog post announcing the summer school next, right?
2. The Meetings page is starting to feel long and cluttered. Do you agree? I had an idea to move everything underneath the calendar into subpages: "**Community Meetings**", "**Conference Sessions**", "**Summer Schools**". Want me to?
> Add "Summer School" nav item

- .github/workflows/PRs.yml
- .github/workflows/pr_checker.py
- _data/projects.yml
- _data/projects_core.yml
- _data/taxonomy.yml
I would like to propose the idea to check PRs with CI so we get a feedback quickly and this also ensures trivial mistakes won't be missed by humans.
So far, only checks for yaml validity and correct usage of keywords in projects but I would be happy to add more and improve the script.
I've run the script locally and here is the output:
```
python3 .github/workflows/pr_checker.py -d
Unlisted keywords for project pySPEDAS: {'data', 'space physics', 'heliophysics', 'magnetospheric physics'}
Project AFINO has no keywords
Unlisted keywords for project GeospaceLAB: {'data_containe'}
Unlisted keywords for project solo-epd-loader: {'data', 'space physics', 'heliophysics'}
Unlisted keywords for project space-packet-parser: {'python', 'data encoding', 'data manipulation', 'space packet protocol', …
```
> Adds bits to check automatically PRs for trivial mistakes

- _pages/meetings/summer_schools/summer_school_24.md
World's smallest PR. The Official Language section for the 2024 summer school said "The official language of the PyHC 2022 Summer School is English" (copypasta for the win). Changes that to 2024.
> summer_school_24: fix the year in "official language" note

- _pages/meetings/community_meetings/spring2024.md
Two quick changes:
- Removes a reference to in-person attendance (and corrects a probable typo on the same line, referring to "spring-related emails", which makes me think of spring rolls for some reason. Mmmmm.)
- Links the Code of Conduct. Maybe that's not the right place, but it should be _somewhere_. Actually I think it should also be an "I agree" checkbox on the registration page, but possibly too late for that.
> Spring meeting 2024 page updates

- .github/workflows/PRs.yml
- .github/workflows/pr_checker.py
- _data/projects.yml
@sapols a little more work for you or related projects maintainers 😅:
```
python3 .github/workflows/pr_checker.py -d
--------------------------------------------------------------------------------
Checking project ACEmag in file /home/jeandet/Documents/prog/GH-stuff/heliophysicsPy.github.io/_data/projects_unevaluated.yml
Project ACEmag misses mandatory fields: {'software_maturity', 'testing', 'license', 'documentation', 'community', 'python3'}
Project ACEmag has no functionality related keyword
Project ACEmag failed checks
--------------------------------------------------------------------------------
Checking project AstrometryAzEl in file /home/jeandet/Documents/prog/GH-stuff/heliophysicsPy.github.io/_data/projects_unevaluated.yml
Project AstrometryAzEl misses mandatory fields: …
```
> Adds more projects description checks and refac to check everything per project

- _pages/docs.html
Closes Issue #301.
Adding a link to our Zenodo Community in the Documents page.
> Add PyHC's Zenodo Community

- _pages/meetings.md
Added the calendar Barbara (and now I) manage to our PyHC page for anyone interested in seeing more general helio/space physics workshops/meetings (many of which are relevant to PyHC members). I'm amenable to not embedding the calendar itself and just having a link. What do you think looks best?
> Adding the helio community events calendar 

- _pages/meetings/summer_schools/summer_school_24.md
- _posts/2024-03-21-summer-school-poster-abstract-submission.markdown
Announcing summer school poster abstract submission through a new blog post, and adding info to the summer school web page. Double checking for any glaring mistakes. If you think I missed anything important on the Google form itself, too, let me know and I'll update that.
> Poster abstract submissions addition to summer school info

- _pages/meetings/summer_schools/summer_school_24.md
Replaces the link to PyHC's YouTube channel with a link to the specific 2024 Summer School livestream playlist.
Merging right away, just FYI @jibarnum
> Update YouTube stream link

- _includes/header.html
We temporarily added a "**Summer School**" nav item to the website to better advertise the 2024 Summer School. Now that the event has passed, it's time to remove that nav item.
> Remove Summer School nav item

- _data/projects.yml
CloudCatalog (_pip install cloudcatalog_) is a specification plus Python client for labeling and retrieving cloud data sets. The shared Cloud Catalog specification can be used for sharing datasets across cloud frameworks as well as exposing cloud archives outside of the cloud. The Python tool is designed for retrieving file catalog (index) files from a specific ID entry in a catalog within a bucket. It also includes search functionality for searching through all data index catalogs found in the bucket list.
For HelioCloud, this specification creates a global data registry of publicly-accessible disks ('HelioDataRegistry'), maintained at the HDRL HelioCloud.org website. Individual dataset owners then define their dataset file catalogs ('CloudCatalog') for each dataset, that resides in the …
> adding CloudCatalog as a PyHC package

- _includes/project_cards.html
- _pyhc_projects/adding_to_pyhc_project_list.md
Resolves #330 
There was a suggestion to not show the "Python 3 standard" requirement in the projects table. This PR removes showing that column and doesn't suggest for it to be included in new reviews.
I did not remove the data from the [project yaml](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/main/_data/projects.yml) though. There are two projects in the table that are not Python 3 compliant. I think they should be moved off the project list but I'll leave that to someone else's discretion. (Both packages haven't really been touched for 14 years. I was the last commit on TomograPy to suggest going to a different package.)
> Removes python3 status from projects table

- _data/projects.yml
Adding [SAMMI](https://github.com/swxsoc/sammi) to the projects page. 
SAMMI is a CDF attribute manager tool to create ISTP-compliant CDF file attributes. It's a collaboration between SWxSOC and the IMAP SDC. It's a small but flexible tool which allows teams to store variable attributes in VCS friendly YAML files and create attributes that align with standard formats. The attributes are returned as Python dictionaries for inputs into data structures such as xarray datasets or astropy datatables. 
SAMMI is released on PyPi and used in both IMAP and SWxSOC processing. 
Grades:
community: good
documentation: good
testing: good
software maturity: good
license: good
The license is under Apache 2.0 - I see PyHC recommends BSD 2 or 3. It's my understanding that Apache 2 and BSD 3 are reasonably …
> Adding SAMMI to projects.yml

- _data/projects.yml
GCMprocpy formerly known as TIEGCMpy, is a post processing and analysis tool for TIE-GCM and WACCM-X outputs. Initially it was created as a replacement for old F90 code for analysis but now has grown to be much more feature rich, versatile and modern. 
- **Open Development**: All code for gcmprocpy is publicly available.
- **Duplication**: gcmprocpy code base is not duplicated or forked from an existing repository
- **Collaboration**: Currently contribution guidelines have not been decided and implemented for gcmprocpy
- **Code of conduct**: Currently code of conduct has not been set for gcmprocpy
- **Improvement Plan**: Build the contribution guidelines and code of conduct for the repository. Task 1
- gcmprocpy has thorough documentation with an automated Google style python docstring to …
> Adding GCMprocpy to PyHC package list

- _data/leaders.yml
- _data/members.yml
- _pages/people.html
This PR adds ORCIDs to the people page. If a member or leader has an "orcid" entry in their respective yaml file, it'll display on the page and link to their ORCID profile.
I've added the easily findable ORCIDs. Others will have to add their own (or tell me what it is so I can add it).
> Add ORCIDs to People page

- _data/projects.yml
Space Packet Parser was recently moved to the LASP Github org. This PR updates the metadata pointing to the repo (and adds a couple of keywords).
> Update space-packet-parser repo location after moving to LASP Github org

- _data/projects.yml
The [asilib](https://aurora-asi-lib.readthedocs.io/) package provides a unified Python 3 framework for accessing, analyzing, and visualizing all-sky imager (ASI) data from various networks like REGO, THEMIS, TREx, and MANGO. It enables tasks such as keogram and movie generation, auroral mapping, and conjunction analysis with other data sources, streamlining research by offering a consistent interface for diverse ASI datasets.
asilib is archived on [PyPI](http://pypi.org/project/asilib/) and [Zenodo](https://zenodo.org/records/15013736).
Grades:
community: good
documentation: good
testing: partially met*
software maturity: good
license: good
*Since our tests require downloading ASI data, they are slower than desired and occasionally crash due to unstable connection. We will mitigate this …
> Added asilib to projects.yml 

- _data/projects.yml
Kaipy is a Python package for analysis and visualization of simulation results from a scientific software package Kaiju. Kaiju includes the Multiscale Atmosphere-Geospace Environment (MAGE) model developed by the NASA DRIVE Center for Geospace Storms as well as other scientific software for simulation of heliospheric environments such as planetary magnetospheres and the solar wind.
- **Open Development**: All code for kaipy is publicly available.
- **Duplication**: kaipy code base is not duplicated or forked from an existing repository.
- **Collaboration**: Currently, contribution guidelines have not been decided and implemented for kaipy.
- **Code of Conduct**: Currently, a code of conduct has not been set for kaipy.
- **Improvement Plan**: Build the contribution guidelines and code of …
> Add kaipy to projects
